# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-13 18:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mypublicapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='metric',
            options={'ordering': ['name'], 'permissions': (('view_metric', 'Can view Metric'),)},
        ),
        migrations.AlterModelOptions(
            name='server',
            options={'ordering': ['name'], 'permissions': (('view_server', 'Can view Server'),)},
        ),
        migrations.AlterModelOptions(
            name='serverproperty',
            options={'ordering': ['name'], 'permissions': (('view_serverproperty', 'Can view Server Property'),)},
        ),
    ]
